networks:
  monitoring:

volumes:
  grafana-data:
  h2data:
  esdata:

services:
  app:
    container_name: crm-order-app
    build: .
    image: samirali3v/crm-order-app:latest
    ports:
      - "8080:8080"
    entrypoint:
      - "java"
      - "-javaagent:/app/opentelemetry-javaagent.jar"
      - "-Dotel.exporter.otlp.endpoint=http://jaeger:4318"
      - "-Dotel.service.name=crm-order-app"
      - "-jar"
      - "app.jar"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_NAME: application
      JAVA_OPTS: "-Xms256m -Xmx512m"
    mem_limit: 512m
    volumes:
      - h2data:/data
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    mem_limit: 128m
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    mem_limit: 128m
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    mem_limit: 64m
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    mem_limit: 64m
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    mem_limit: 350m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - monitoring

  fluentbit:
    image: fluent/fluent-bit:2.2-debug
    container_name: fluentbit
    mem_limit: 50m
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: jaeger
    mem_limit: 128m
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - monitoring
