services:
  app:
    container_name: crm-order-app
    build: .
    image: samirali3v/crm-order-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_NAME: application
      JAVA_TOOL_OPTIONS: ""        # OTEL agenti PRODDAN TAM SÖNDÜRÜR
      JAVA_OPTS: "-Xms256m -Xmx512m"
    mem_limit: 600m
    volumes:
      - h2data:/data

volumes:
  h2data:
