[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*

[OUTPUT]
    Name            es
    Match           docker.*
    Host            elasticsearch
    Port            9200
    Index           fluentbit-logs
    Suppress_Type_Name On