server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/crmdb
spring.datasource.username=crmuser
spring.datasource.password=crmpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
